.dockerignore, Dockerfile, local.Dockerfile, package-lock.json, package.json, src/app.js, src/app/toy/index.js, src/lib/config.js, src/lib/settings.js, src/lib/settings.test.js, src/locales/cy/default.yml, src/locales/cy/pages.errors.yml, src/locales/en/default.yml, src/locales/en/pages.errors.yml, src/views/errors/error.html
Add Express and everything else required to run a minimal webserver, including a Dockerfile.
This currently display an error page, as no routes are implemented.
CSS is not built due to an undiagnosed issue running the minification. This will be fixed in a future iteration.
- [OJ-1399](https://govukverify.atlassian.net/browse/OJ-1399)
[OJ-1399]: https://govukverify.atlassian.net/browse/OJ-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 1399/add minimal express server

.github/workflows/codeql.yml, .github/workflows/pre-commit.yml, .github/workflows/unit-tests.yml
Add GHA for running tests/linting and pre-commit hooks
- [OJ-1569](https://govukverify.atlassian.net/browse/OJ-1569)
[OJ-1569]: https://govukverify.atlassian.net/browse/OJ-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add GHA for linting and pre-commit hooks

package-lock.json, package.json, test/browser/cucumber.js, test/browser/features/hello-world.feature, test/browser/pages/print.js, test/browser/step_definitions/hello-world.js
=> Oj 1456 configure cucumber browser tests for fe

.github/workflows/i18n.yml, package.json, src/app/toy/controllers/choose-favourite.js, src/app/toy/fields.js, src/app/toy/index.js, src/app/toy/steps.js, src/locales/cy/fields.yml, src/locales/cy/pages.errors.yml, src/locales/cy/pages.yml, src/locales/en/fields.yml, src/locales/en/pages.errors.yml, src/locales/en/pages.yml, src/views/errors/error.html, src/views/errors/page-not-found.html, src/views/errors/session-ended.html, src/views/toy/choose-favourite.html, src/views/toy/intro.html, test/imposter/private-api-config.yaml, test/imposter/private-api.yaml
- Add pages to the Toy API using HMPO Form Wizard
- Add Imposter stub to run a complete journey through the UI
=> Oj 1419/add pages

.github/workflows/pre-merge.yml
Added GHA to run browser tests
- [OJ-1472](https://govukverify.atlassian.net/browse/OJ-1472)
[OJ-1472]: https://govukverify.atlassian.net/browse/OJ-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 1472 GitHub actions to run fe cucumber browser tests

.github/workflows/post-merge-deploy.yaml, deploy/template.yaml
Can deploy this front end via secure pipelines.
Front end can be viewed via: https://review-toy.dev.account.gov.uk/
To be inline with all other repos for deployment
- [OJ-1400](https://govukverify.atlassian.net/browse/OJ-1400)
[OJ-1400]: https://govukverify.atlassian.net/browse/OJ-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 1400 deploy fe to build and staging using secure pipelines

Dockerfile, local.Dockerfile
Use the npm task to build static assets
=> chore: Fix building of assets in Dockerfiles

README.md
- Added documentation on usage of [pre-commit](https://pre-commit.com/)
- Added documentation on Codeowners
=> docs: Update readme with details of pre-commit

test/imposter/private-api-config.yaml
=> fix: Add statusCode 200 to favourite stub

src/app/toy/controllers/choose-favourite.js, src/app/toy/fields.js, src/locales/cy/fields.yml, src/locales/en/fields.yml, test/browser/features/happy.feature, test/browser/pages/choose-favourite.js, test/browser/step_definitions/choose-favourite.js, test/imposter/private-api-config.yaml
Add test for choosing a favourite toy
- [OJ-1454](https://govukverify.atlassian.net/browse/OJ-1454)
[OJ-1454]: https://govukverify.atlassian.net/browse/OJ-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: Add test for save favourite

.github/workflows/pre-merge.yml
Rename smoke tests to browser tests
=> chore: Rename smoke tests to browser tests

test/browser/features/error-authorisation.feature, test/browser/features/happy.feature, test/browser/step_definitions/intro.js
Use consistent language to describe navigating away from a page.
- `continue from` works better than `continue to` as there is knowledge about the current page
=> chore: Use 'continue from' in feature file

test/browser/step_definitions/relying-party.js
=> fix: Correctly match full name in step definition

deploy/template.yaml
Updated  template to include VPC Link and updated health checks
To fix the deployment issyes
- [OJ-1769](https://govukverify.atlassian.net/browse/OJ-1769)
[OJ-1769]: https://govukverify.atlassian.net/browse/OJ-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: toy front deployment issues

deploy/template.yaml
Updated API Gateway URL to include the VPCE endpoint
To fix the api gateway issues
- [OJ-1916](https://govukverify.atlassian.net/browse/OJ-1916)
[OJ-1916]: https://govukverify.atlassian.net/browse/OJ-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> oj-1916 update url for private api gateway

deploy/template.yaml
template had error in api gateway url
Added missing $
- [OJ-1916](https://govukverify.atlassian.net/browse/OJ-1916)
[OJ-1916]: https://govukverify.atlassian.net/browse/OJ-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> oj-1916 update vpcid syntax

test/browser/package-lock.json, test/browser/package.json
Add dotenv to `tests/browser/package.json`
=> deps: Add dotenv

package-lock.json, package.json, src/app.js, src/locales/cy/default.yml, src/locales/en/default.yml
- Update to latest version of @govuk-one-login/di-ipv-cri-common-express@3.2.0
- Update locales to fix breaking change
=> Update to latest version of @govuk-one-login/di-ipv-cri-common-express@3.2.0

src/app.js
Add support for getAssetPath functionality. This fix is required for the first stage of the CDN work for static assets.
=> feat: Set assetPath for res.locals

.github/workflows/browser.yml, .github/workflows/post-merge-deploy.yaml, .pre-commit-config.yaml, .secrets.baseline, CODEOWNERS, Dockerfile, deploy/template.yaml
IPS-296 adding dynatrace layer
IPS-296 adding dynatrace layer
- [IPS-296](https://govukverify.atlassian.net/browse/IPS-296)
[IPS-296]: https://govukverify.atlassian.net/browse/IPS-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-296 Added Dynatrace Integration

.github/workflows/post-merge-deploy.yaml
Add workflow dispatch to run workflow
To test dyntrace changes
- [IPS-440](https://govukverify.atlassian.net/browse/IPS-440)
[IPS-440]: https://govukverify.atlassian.net/browse/IPS-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-440-workflow-dynatrace-login

.eslintignore, .eslintrc.js, .github/workflows/pre-commit.yml, .github/workflows/unit-tests.yml, .pre-commit-config.yaml, .prettierignore, .prettierrc.json, .secrets.baseline, jest.config.js, package-lock.json, package.json, sonar-project.properties, src/lib/settings.test.js, test/browser/step_definitions/choose-favourite.js, test/browser/step_definitions/intro.js, test/browser/step_definitions/relying-party.js, test/browser/support/setup.js
Apply standardised repo config from other repos
- Update pre-commit hooks
- Remove a misconfigured Checkov hook
- Add an ESLint hook
- Address linting issues
- Use the prettier and jest plugins in ESLint
- Apply the recommended rules and styles for jest only for test files
- Install dev dependencies before running pre-commit to get ESLint plugins
- Allow unused variables if their names start with an underscore in test files
- Do linting as part of the pre-commit checks
- Update the linting commands
- Update the `.secrets.baseline` file to exclude specific keywords and files
- Update `package.json` to remove duplicated or unnecessary config
- Update linting and testing packages
- Set correct filters for source and test files for SonarCloud analysis
=> OJ-1495: Update repo config

README.md, jest.config.js, sonar-project.properties
- Ignore form-wizard configuration in jest.config.js
- Ignore form-wizard config in sonar.properties
=> OJ-2268: Ignore config code for test coverage

src/locales/cy/default.yml, src/locales/en/default.yml
Footer content and interactions changed to match standard journey behaviour
YAML content files have been updated.
Footer content should remain the same across the user journey to meet [the new **Consistent Help** WCAG 2.2 criteria](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help).
=> CNUCD: Update footer links to standardise footer content

jest.config.js
=> Update jest.config.js to ignore config.js

package-lock.json, package.json, src/app.js, src/assets/scss/application.scss
[OJ-2565](https://govukverify.atlassian.net/browse/OJ-2565)
Use updated language toggle and cri-common-express
-[OJ-2565](https://govukverify.atlassian.net/browse/OJ-2565)
[OJ-2565]: https://govukverify.atlassian.net/browse/OJ-2565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2565]: https://govukverify.atlassian.net/browse/OJ-2565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Use updated language toggle and cri-common-express

.gitignore, .secrets.baseline, deploy/template.yaml
=> Test named load balancer

.gitignore, .secrets.baseline, deploy/template.yaml
Reverts govuk-one-login/ipv-cri-toy-front#249
=> Revert "Test named load balancer"

package-lock.json, package.json, src/lib/config.js
[OJ-2571] Accessibility Fix - Focus on Error Summary
updated di-ipv-cri-common-express to include the fix
[OJ-2571](https://govukverify.atlassian.net/browse/OJ-2571)
[OJ-2571]: https://govukverify.atlassian.net/browse/OJ-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2571]: https://govukverify.atlassian.net/browse/OJ-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update common express to include the fix

.github/workflows/post-merge-deploy.yaml
=> IPA-227 fix deploy workflow
